### ISSUE TITLE
Boas iniciativas de Projectos

### ISSUE THREAD

**Issue by adolfomonteiro** [jesimielnobrega/Aulas-React_Typescript#1]
Comece mesmo a desenvolver Pojectos do Gênero wy, vais ser mais fera ainda, eu vou seguir o seu exemplo...

Para mim **Web** e **mobile** são os _Futuros_ ....**Futuros**

**Comment by adolfomonteiro** [comment]
> Comece mesmo a desenvolver Pojectos do Gênero wy, vais ser mais fera ainda, eu vou seguir o seu exemplo...
> 
> Para mim **Web** e **mobile** são os _Futuros_ ....**Futuros**

**Comment by adolfomonteiro** [comment]
@jesimielnobrega   Essa mensagem é para ti...

**Comment by jesimielnobrega** [comment]
Valeu mano 
Irei continuar
